version: 1
build:
  binary: razorChaind
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 100000000uatom
  - 100000000000000000000stake
- name: bob
  coins:
  - 5000000000000stake
faucet:
  name: bob
  coins:
  - 10stake
  host: 0.0.0.0:4500
client:
  typescript:
    path: ts-client
  hooks:
    path: react/src/hooks
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: stake
    evm:
      params:
        evm_denom: stake
    gov:
      deposit_params:
        min_deposit:
        - amount: "10000000"
          denom: stake
    mint:
      params:
        mint_denom: stake
    staking:
      params:
        bond_denom: stake
  chain_id: rzrd_771-1
validators:
- name: alice
  bonded: 100000000000000000000stake
